version: 0.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
  init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  #n
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./ArchaicQuestII.sln --verbosity m
  build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./ArchaicQuestII.sln
build:
  publish_wap: true
  publish_core_console: true
  verbosity: minimal
after_build:
  #1
artifacts:
 - path: '\bin\Debug\netcoreapp2.2\publish'
   name: WebSite
   type: WebDeployPackage
deploy:
- provider: FTP
  host: 217.194.213.132
  protocol: ftp
  username: aqplay
  password:
    secure: B7a8pFUW0uUZZvLBYd3QeQ==