 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     

     steps:
       - checkout
       - run: dotnet build -c Release -o ../artifacts
       - run: dotnet publish -c Release -o ../artifacts
       - run: echo $SSH_USER
       - run:
            name: Deploy 
            command: |
                echo ${SSH_USER}
                echo ${SSH_HOST}
                echo ${SSH_USER}@${SSH_HOST}:${SSH_PATH}
                scp -r ../artifacts ssh $SSH_USER@${SSH_HOST}:$SSH_PATH
             